#!/usr/bin/env bash
# Path to the file
file="/etc/passwd"
while IFS=: read -r username _ userid _ homedir _; do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $homedir"
done < "$file"

