#!/usr/bin/env bash
#a script displaying best school 10 times using while loop
i=1
while [ $i -lt 11 ]
do
if [ $i -eq 4 ];then
echo "bad luck"
elif [ $i -eq 8 ];then
echo "good luck"
else
echo "Best School"
fi
((i++))
done


