#!/usr/bin/env bash
# Script: Display content of current directory in list format, showing only part of name after first dash and excluding hidden files

for file in *; do
    if [[ ! $file == .* ]]; then
        name=$(echo "$file" | cut -d'-' -f2-)
        echo "$name"
    fi
done

